Add OSGi metadata to the S2 geometry library
google/s2-geometry-library-java pull request #28
Opened 2021-07-28 08:25 UTC by timothyjward

In order to use this library in an OSGi framework it needs to include OSGi metadata. Rather than users having to repackage the code, it would be easier if the library jar already contained OSGi bundle metadata.

2021-08-11 15:43 UTC, timothyjward commented
Rebased to fix the merge issue

2021-08-12 02:13 UTC, eengle commented
Can you address the CLA issue?

On Wed, Aug 11, 2021 at 8:43 AM Tim Ward ***@***.***> wrote:

> Rebased to fix the merge issue
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/s2-geometry-library-java/pull/28#issuecomment-896936376>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA4DAANALCSGNRZRDVR4PM3T4KLBTANCNFSM5BD3H4KQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-18 11:58 UTC, timothyjward commented
@googlebot I signed it!

2021-09-09 08:02 UTC, timothyjward commented
> Can you address the CLA issue?

Is there anything further that you need me to do?

2021-09-10 16:20 UTC, eengle requested changes
Thanks for adding the jar plugin as well. Can you update the description?

2021-09-10 16:20 UTC, eengle commented
CLAs look good to me now. Sorry that took awhile.

2021-09-15 10:25 UTC, timothyjward commented
> Thanks for adding the jar plugin as well. Can you update the description?

I've added a more descriptive commit message

2021-09-16 03:58 UTC, merged

2021-09-16 03:58 UTC, eengle commented
Thanks!